### ISSUE TITLE
Misunderstanding on flush calculating

### ISSUE THREAD

**Issue by dbjock** [TroyWilliams3687/cribbage#1]
There's a flaw in the logic in calculating flushes. Score of 5 can occur on a normal hand AND a crib hand. Though a crib hand can not score 4 on a flush, as the crib hand cards must all be the same suit as the cut/starter card therefore a score of 5.
https://bicyclecards.com/how-to-play/cribbage/ (searching for flush) will provide these lines:
- Flush. Four cards of the same suit in hand 4 (excluding the crib, and the starter)
- Four cards in hand or crib of the same 5 suit as the starter
  (There is no count for four-flush in the crib that is not of same suit as the starter)

I'm not sure how to call `score_hand` or `score_hand_breakdown` as there doesn't seem to be anyway to determine if the hand is a crib hand or not.

**Comment by dbjock** [comment]
Here is a oneliner which will fix this and should be in the `score_hand` and `score_hand_breakdown`
```python
flush = 0 if hand_scores["flush"] == 4 and five_card_flush else hand_scores["flush"]
```
I believe the comments will need to be adjusted to reflect the logic, to apply to the flush rules.

**Comment by TroyWilliams3687** [comment]
There is an option in `score_hand`, called `five_card_flush`. It is `false` be default. If you set it to true, it will only score a flush if there are 5 cards. If you were counting a crib hand, you would set that value to true.

`score_hand_breakdown` also has the same argument.

I designed these methods to assist in analyzing (and learning) a hand. The idea would be if you dealt a game you could input the cards in your hand to get a scoring breakdown to decide the best discard strategy. I didn't really design it to tally up the scores at the end - you can certainly do that by setting the appropriate option depending on whether you are scoring your hand or your crib.

I do have a blog post that describes the usage of the code: https://www.bluebill.net/cribbage2/

I hope this helps.
